// Generated by scripts/sync_app_contract.py; edit contracts/app-api-v1.ts.
/** Canonical mobile wire contract. Generate copies with scripts/sync_app_contract.py. */
export interface WirePoint {
  t: string;
  v: number | null;
}

export type Direction = "up" | "down" | "neutral";

export interface Handshake {
  name: string;
  version: number;
  minSupportedClient: number;
  web: string;
  screens: Record<string, string>;
}

export interface Vital {
  key: string;
  label: string;
  value: number | null;
  unit: string;
  decimals: number;
  series: WirePoint[];
  change12: number | null;
  good: Direction;
}

export interface Mover {
  key: string;
  label: string;
  prev: number | null;
  curr: number | null;
  decimals: number;
  good: Direction;
  note: string | null;
}

export interface TransmissionItem {
  key: string;
  label: string;
  value: number | null;
  unit: string | null;
  decimals: number;
  effect: {
    metric: string;
    nominal?: number | null;
    real?: number | null;
    deflator?: number | null;
    deflatorBasis?: string;
    low24m?: number | null;
    href: string;
  };
}

export interface Flag {
  code: string;
  active: boolean;
  /** The rule the flag fired by, printed under it. Never a client-side string. */
  rule: string;
  operands: Record<string, number | null>;
}

export interface StandingRow {
  rank: number;
  ticker: string;
  name: string;
  car: number | null;
}

export interface PulseInsight {
  text?: string;
  tone?: string;
  [k: string]: unknown;
}

export interface Overview {
  record: { period: string | null; label: string; vs: string };
  coverage: { banks: number };
  levels: {
    /** Thousand TL — normalised server-side. The BDDK bulletin this comes from
     *  is denominated in MILLION TL while the audit tables are in thousand;
     *  the route converts so the client has one scale. See `units`. */
    totalAssets: number | null;
    assetsYoY: number | null;
    loansYoY: number | null;
    depositsYoY: number | null;
  };
  units: { amounts: "thousand TL"; rates: "percent" };
  // NOTE: no market tape. The BIST/FX/commodity strip the website shows is
  // Yahoo-sourced, and Yahoo's terms forbid redistribution — which a store
  // listing makes formal in a way a web page does not. The API no longer sends
  // it and the app no longer renders it. USD/TRY still reaches the transmission
  // block, from TCMB EVDS instead.
  vitals: Vital[];
  movers: Mover[];
  transmission: TransmissionItem[];
  flags: Flag[];
  standings: { period: string | null; best: StandingRow[]; thinnest: StandingRow[] };
  pulse: unknown;
  ahead: { kind: string; when: string; date: string; rule: string; record: string | null }[];
}

export interface BankRow {
  ticker: string;
  name: string;
  type: string | null;
  typeLabel: string | null;
  /** True for Takasbank — a CCP whose ratios answer a different question. Never
   *  rank it against deposit-funded lenders. */
  peerExcluded: boolean;
  /** Thousand TL. */
  totalAssets: number | null;
  // All percentage POINTS (30.4 = 30.4%) — normalised server-side. See `units`.
  roe: number | null;
  roeAdjusted: number | null;
  npl: number | null;
  car: number | null;
  cet1: number | null;
  nim: number | null;
  costIncome: number | null;
  periodsHeld: number;
  latestPeriodHeld: string | null;
}

export interface BankList {
  period: string | null;
  /** The whole universe we hold filings for. */
  count: number;
  /** The rankable subset. Rank and colour-scale off this, never off `count`. */
  peers: number;
  /** Declared, not assumed. Every ratio here is percentage POINTS — the route
   *  normalises the fraction-scaled metrics before sending. */
  units: { amounts: "thousand TL"; rates: "percent" };
  rows: BankRow[];
}

/** "pct" = stored as a FRACTION (0.155 → 15.5%); "pts" = already in percentage
 *  POINTS (15.5 → 15.5%). Getting this wrong is a silent 100× error. */
export type MetricUnit = "pct" | "pts" | "trn" | "bn" | "raw" | "mult";

export interface ScorecardMetric {
  key: string;
  label: string;
  short: string;
  unit: MetricUnit;
  decimals: number;
  direction: "higher_better" | "higher_worse" | "neutral";
  rule: string | null;
  value: number | null;
  series: WirePoint[];
}

export interface NewsEntry {
  id: string;
  publishedAt: string;
  title: string;
  summary: string | null;
  url: string;
  source: string;
  category: string | null;
  language: string;
  tickers?: string[];
}

export interface BankDetail {
  ticker: string;
  name: string;
  type: string | null;
  typeLabel: string | null;
  peerExcluded: boolean;
  period: string | null;
  coverage: { periodsHeld: number; latestPeriodHeld: string | null };
  /** False for a bank the ratio panel refuses to hold (a CCP). The filings are
   *  real; the peer ratios are simply not computed for it. */
  scorecardAvailable: boolean;
  scorecardNote: string | null;
  scorecard: ScorecardMetric[];
  earningsQuality: {
    roe: number | null;
    roeAdjusted: number | null;
    freeProvision: number | null;
  };
  profile: {
    period: string;
    branchesTotal: number | null;
    branchesDomestic: number | null;
    branchesForeign: number | null;
    personnel: number | null;
  } | null;
  stages: {
    period: string;
    stage1: number | null;
    stage2: number | null;
    stage3: number | null;
    total: number | null;
    coverage1: number | null;
    coverage2: number | null;
    coverage3: number | null;
  } | null;
  news: NewsEntry[];
  web: string;
}

export interface Economy {
  headline: Record<string, number | null>;
  series: Record<string, WirePoint[]>;
  units: Record<string, string>;
  source: string;
}

export interface BriefingCategory {
  name: string;
  bullets: { text: string; source_ids: string[] }[];
}

export interface NewsFeed {
  source: string;
  count: number;
  items: NewsEntry[];
  briefing: {
    generatedAt: string;
    windowDays: number;
    itemCount: number;
    model: string;
    categories: BriefingCategory[];
  } | null;
}

export const CONTRACT_VERSION = 1;
export class ContractError extends Error {
  constructor(path: string) { super(`Invalid mobile API response at ${path}`); this.name = "ContractError"; }
}
type Check<T> = (value: unknown, path: string) => T;
const fail = (path: string): never => { throw new ContractError(path); };
const str: Check<string> = (v, p) => typeof v === "string" ? v : fail(p);
const num: Check<number> = (v, p) => typeof v === "number" && Number.isFinite(v) ? v : fail(p);
const bool: Check<boolean> = (v, p) => typeof v === "boolean" ? v : fail(p);
const integer: Check<number> = (v, p) => Number.isSafeInteger(num(v, p)) && (v as number) >= 0 ? v as number : fail(p);
const nullable = <T>(check: Check<T>): Check<T | null> => (v, p) => v === null ? null : check(v, p);
const optional = <T>(check: Check<T>): Check<T | undefined> => (v, p) => v === undefined ? undefined : check(v, p);
const array = <T>(check: Check<T>): Check<T[]> => (v, p) => Array.isArray(v) ? v.map((item, i) => check(item, `${p}[${i}]`)) : fail(p);
const object = <T>(shape: { [K in keyof T]-?: Check<T[K]> }): Check<T> => (v, p) => {
  if (v === null || typeof v !== "object" || Array.isArray(v)) return fail(p);
  for (const key of Object.keys(shape) as (keyof T & string)[]) {
    shape[key]((v as Record<string, unknown>)[key], `${p}.${key}`);
  }
  return v as T; // Every declared field checked above; additive fields are allowed.
};
const record = <T>(check: Check<T>): Check<Record<string, T>> => (v, p) => {
  if (v === null || typeof v !== "object" || Array.isArray(v)) return fail(p);
  for (const [key, item] of Object.entries(v)) check(item, `${p}.${key}`);
  return v as Record<string, T>;
};
const requiredRecord = <T>(check: Check<T>, keys: readonly string[]): Check<Record<string, T>> => (v, p) => {
  const result = record(check)(v, p);
  for (const key of keys) if (!Object.prototype.hasOwnProperty.call(result, key)) fail(`${p}.${key}`);
  return result;
};
export const ECONOMY_UNITS = {
  gdpGrowth: "% y/y", ipGrowth: "% y/y", unemployment: "%", cpiYoY: "% y/y",
  cpiMoM: "% m/m", exp12m: "%", fundingMonthly: "%", realRate: "%", usdtry: "TRY",
  reer: "index", ca12m: "USD bn, 12m", budgetPctGdp: "% GDP, 12m",
} as const;
const economyUnits: Check<Economy["units"]> = (v, p) => {
  const units = record(str)(v, p);
  for (const [key, unit] of Object.entries(ECONOMY_UNITS)) if (units[key] !== unit) fail(`${p}.${key}`);
  return units;
};
const oneOf = <T extends string>(...values: T[]): Check<T> => (v, p) => values.includes(v as T) ? v as T : fail(p);
const n = nullable(num), s = nullable(str);
const direction = oneOf("up", "down", "neutral");
const point = object<WirePoint>({ t: str, v: n });
const units = object<BankList["units"]>({ amounts: oneOf("thousand TL"), rates: oneOf("percent") });
const newsEntry = object<NewsEntry>({ id: str, publishedAt: str, title: str, summary: s, url: str, source: str, category: s, language: str, tickers: optional(array(str)) });
const standing = object<StandingRow>({ rank: integer, ticker: str, name: str, car: n });
const metric = object<ScorecardMetric>({ key: str, label: str, short: str, unit: oneOf("pct", "pts", "trn", "bn", "raw", "mult"), decimals: integer, direction: oneOf("higher_better", "higher_worse", "neutral"), rule: s, value: n, series: array(point) });
export interface Payloads { handshake: Handshake; overview: Overview; banks: BankList; bank: BankDetail; economy: Economy; news: NewsFeed }
export const checks: { [K in keyof Payloads]: Check<Payloads[K]> } = {
  handshake: object<Handshake>({ name: str, version: integer, minSupportedClient: integer, web: str, screens: record(str) }),
  banks: object<BankList>({ period: s, count: integer, peers: integer, units,
    rows: array(object<BankRow>({ ticker: str, name: str, type: s, typeLabel: s, peerExcluded: bool, totalAssets: n, roe: n, roeAdjusted: n, npl: n, car: n, cet1: n, nim: n, costIncome: n, periodsHeld: integer, latestPeriodHeld: s })) }),
  bank: object<BankDetail>({ ticker: str, name: str, type: s, typeLabel: s, peerExcluded: bool, period: s,
    coverage: object<BankDetail["coverage"]>({ periodsHeld: integer, latestPeriodHeld: s }), scorecardAvailable: bool, scorecardNote: s, scorecard: array(metric),
    earningsQuality: object<BankDetail["earningsQuality"]>({ roe: n, roeAdjusted: n, freeProvision: n }),
    profile: nullable(object<NonNullable<BankDetail["profile"]>>({ period: str, branchesTotal: n, branchesDomestic: n, branchesForeign: n, personnel: n })),
    stages: nullable(object<NonNullable<BankDetail["stages"]>>({ period: str, stage1: n, stage2: n, stage3: n, total: n, coverage1: n, coverage2: n, coverage3: n })), news: array(newsEntry), web: str }),
  economy: object<Economy>({
    headline: requiredRecord(n, ["gdpGrowth", "cpiYoY", "unemployment", "fundingCost", "realRate", "usdtry", "ca12m", "budgetPctGdp"]),
    series: requiredRecord(array(point), Object.keys(ECONOMY_UNITS)), units: economyUnits, source: str }),
  news: object<NewsFeed>({ source: str, count: integer, items: array(newsEntry), briefing: nullable(object<NonNullable<NewsFeed["briefing"]>>({ generatedAt: str, windowDays: integer, itemCount: integer, model: str,
    categories: array(object<BriefingCategory>({ name: str, bullets: array(object<BriefingCategory["bullets"][number]>({ text: str, source_ids: array(str) })) })) })) }),
  overview: object<Overview>({ record: object<Overview["record"]>({ period: s, label: str, vs: str }), coverage: object<Overview["coverage"]>({ banks: integer }),
    levels: object<Overview["levels"]>({ totalAssets: n, assetsYoY: n, loansYoY: n, depositsYoY: n }), units,
    vitals: array(object<Vital>({ key: str, label: str, value: n, unit: str, decimals: integer, series: array(point), change12: n, good: direction })),
    movers: array(object<Mover>({ key: str, label: str, prev: n, curr: n, decimals: integer, good: direction, note: s })),
    transmission: array(object<TransmissionItem>({ key: str, label: str, value: n, unit: s, decimals: integer,
      effect: object<TransmissionItem["effect"]>({ metric: str, nominal: optional(n), real: optional(n), deflator: optional(n), deflatorBasis: optional(str), low24m: optional(n), href: str }) })),
    flags: array(object<Flag>({ code: str, active: bool, rule: str, operands: record(n) })),
    standings: object<Overview["standings"]>({ period: s, best: array(standing), thinnest: array(standing) }), pulse: (v) => v,
    ahead: array(object<Overview["ahead"][number]>({ kind: str, when: str, date: str, rule: str, record: s })) }),
};
export function decode<K extends keyof Payloads>(kind: K, value: unknown): Payloads[K] { return checks[kind](value, kind); }
export function responseKind(path: string): keyof Payloads {
  const route = path.split("?")[0].replace(/\/$/, "");
  const tail = route.replace(/^\/api\/app\/v1/, "");
  if (route === "/api/app/v1") return "handshake";
  if (!route.startsWith("/api/app/v1/")) return fail(path);
  if (/^\/banks\/[^/]+$/.test(tail)) return "bank";
  if (["overview", "banks", "economy", "news"].includes(tail.slice(1))) return tail.slice(1) as keyof Payloads;
  return fail(path);
}
export function decodeResponse<T>(path: string, value: unknown): T {
  return decode(responseKind(path), value) as T;
}
export function supported(handshake: Handshake, build: number): boolean {
  return handshake.version === CONTRACT_VERSION && Number.isSafeInteger(build) && build >= handshake.minSupportedClient;
}
export function cacheKey(origin: string, path: string): string {
  return `carthago:${CONTRACT_VERSION}:${encodeURIComponent(origin)}:${path}`;
}
export interface CacheEnvelope<T> { cachedAt: number; data: T }
export function decodeCache<T>(origin: string, path: string, raw: string): CacheEnvelope<T> {
  const envelope = JSON.parse(raw);
  if (envelope.version !== CONTRACT_VERSION || envelope.origin !== origin || !Number.isFinite(envelope.cachedAt) || envelope.cachedAt <= 0) return fail("cache");
  return { cachedAt: envelope.cachedAt, data: decodeResponse<T>(path, envelope.data) };
}
export function encodeCache<T>(origin: string, path: string, data: T, now = Date.now()): string {
  decodeResponse(path, data);
  return JSON.stringify({ version: CONTRACT_VERSION, origin, cachedAt: now, data });
}
