/**
 * /regulation — central-bank + banking-regulator announcements.
 *
 * Top: a weekly Kimi-generated thematic briefing (BBVA-style 6-column
 * grid) summarizing what changed in Turkish banking regulation. Below:
 * the raw TCMB + BDDK feeds for traceability and drill-down.
 *
 * Briefing is generated by scripts/summarize_regulations.py (Sunday
 * cron). Dashboard reads the latest row from regulation_briefings — no
 * LLM calls on page load.
 */
import Link from "next/link";
import {
  latestRegulationBriefing,
  newsBySource,
  newsLookupBySourceIds,
  newsSourceSummary,
  sourceLabel,
  type Briefing,
  type NewsItem,
  type NewsSource,
} from "@/app/lib/news";

export const dynamic = "force-dynamic";

const SOURCE_DESCRIPTIONS: Record<"tcmb" | "bddk", string> = {
  tcmb: "Central Bank of Türkiye — monetary policy + market operations press releases (English).",
  bddk: "Banking Regulation and Supervision Agency — official announcements (Turkish).",
};

const SOURCE_COLOR: Record<NewsSource, string> = {
  kap: "border-l-[#7a0d2e]",
  tcmb: "border-l-[#1f4068]",
  bddk: "border-l-[#0f7b6c]",
};

function fmtDate(iso: string): string {
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return iso.slice(0, 10);
  return d.toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" });
}

function NewsCard({ item }: { item: NewsItem }) {
  return (
    <a
      href={item.url}
      target="_blank"
      rel="noopener noreferrer"
      className={`block rounded-md border border-neutral-200 border-l-4 ${SOURCE_COLOR[item.source as NewsSource]} bg-white p-3 hover:bg-neutral-50 transition`}
    >
      <div className="flex items-baseline justify-between gap-2 text-[10px] text-neutral-500 uppercase tracking-wide mb-1">
        <span className="tabular-nums">{fmtDate(item.published_at)}</span>
        <span className="text-neutral-400">{sourceLabel(item.source)}</span>
      </div>
      <div className="text-sm text-neutral-900 leading-snug line-clamp-3">{item.title}</div>
      {item.summary && (
        <div className="text-xs text-neutral-600 mt-1 line-clamp-2">{item.summary}</div>
      )}
    </a>
  );
}

function SourceColumn({ source, items }: { source: "tcmb" | "bddk"; items: NewsItem[] }) {
  return (
    <section className="space-y-3">
      <header className="space-y-0.5">
        <h2 className="text-base font-semibold text-neutral-900">{sourceLabel(source)}</h2>
        <p className="text-xs text-neutral-500">{SOURCE_DESCRIPTIONS[source]}</p>
      </header>
      <div className="space-y-2">
        {items.length === 0 ? (
          <div className="text-xs text-neutral-500 italic">No items yet.</div>
        ) : (
          items.map((it) => <NewsCard key={`${it.source}-${it.external_id}`} item={it} />)
        )}
      </div>
    </section>
  );
}

function BriefingWidget({
  briefing,
  sourceLookup,
}: {
  briefing: Briefing;
  sourceLookup: Map<string, { title: string; url: string }>;
}) {
  return (
    <section className="space-y-3">
      <header className="flex items-baseline justify-between flex-wrap gap-2">
        <div>
          <h2 className="text-base font-semibold text-neutral-900">This Week's Regulatory Briefing</h2>
          <p className="text-xs text-neutral-500">
            AI-synthesized summary of {briefing.item_count} TCMB &amp; BDDK items over the past {briefing.window_days} days
          </p>
        </div>
        <div className="text-[11px] text-neutral-400 tabular-nums">
          generated {fmtDate(briefing.generated_at)} · {briefing.model}
        </div>
      </header>
      <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">
        {briefing.categories.map((cat) => (
          <div key={cat.name} className="rounded-lg border border-neutral-200 bg-white p-4 shadow-sm">
            <h3 className="text-sm font-semibold text-neutral-900 mb-2">{cat.name}</h3>
            <ul className="space-y-2">
              {cat.bullets.map((b, i) => (
                <li key={i} className="text-xs text-neutral-700 leading-snug">
                  <span className="text-neutral-400 mr-1">•</span>
                  {b.text}
                  {b.source_ids.length > 0 && (
                    <span className="ml-1 text-[10px] text-neutral-400">
                      {b.source_ids.map((id, idx) => {
                        const item = sourceLookup.get(id);
                        return (
                          <span key={id}>
                            {idx > 0 && ", "}
                            {item ? (
                              <a
                                href={item.url}
                                target="_blank"
                                rel="noopener noreferrer"
                                className="hover:text-neutral-700 underline-offset-2 hover:underline"
                                title={item.title}
                              >
                                {id}
                              </a>
                            ) : (
                              <span>{id}</span>
                            )}
                          </span>
                        );
                      })}
                    </span>
                  )}
                </li>
              ))}
            </ul>
          </div>
        ))}
      </div>
    </section>
  );
}

export default async function RegulationPage() {
  const [briefing, tcmb, bddk, summary] = await Promise.all([
    latestRegulationBriefing(),
    newsBySource("tcmb", 50),
    newsBySource("bddk", 50),
    newsSourceSummary(),
  ]);

  // Build lookup for source-id chips in the briefing.
  const sourceLookup = briefing
    ? await newsLookupBySourceIds(
        briefing.categories.flatMap((c) =>
          c.bullets.flatMap((b) =>
            b.source_ids.map((id) => {
              const [src, ext] = id.split(":", 2);
              return { source: src, external_id: ext };
            }),
          ),
        ),
      )
    : new Map();

  const tcmbStats = summary.find((s) => s.source === "tcmb");
  const bddkStats = summary.find((s) => s.source === "bddk");

  return (
    <main className="px-8 py-8 space-y-8">
      <header className="space-y-1">
        <h1 className="text-2xl font-semibold tracking-tight">Regulation</h1>
        <p className="text-sm text-neutral-500">
          Central-bank press releases (TCMB) and banking-regulator board decisions (BDDK) — refreshed daily,
          thematic briefing refreshed weekly.
        </p>
        <div className="flex flex-wrap gap-4 text-xs text-neutral-500 pt-2">
          {tcmbStats && (
            <div>
              <span className="font-semibold text-neutral-700">TCMB</span> — {tcmbStats.total} items
              {tcmbStats.latest && (
                <span className="text-neutral-400"> · latest {fmtDate(tcmbStats.latest)}</span>
              )}
            </div>
          )}
          {bddkStats && (
            <div>
              <span className="font-semibold text-neutral-700">BDDK</span> — {bddkStats.total} items
              {bddkStats.latest && (
                <span className="text-neutral-400"> · latest {fmtDate(bddkStats.latest)}</span>
              )}
            </div>
          )}
          <Link
            href="/banks"
            className="text-neutral-600 underline hover:text-neutral-900"
          >
            Per-bank disclosures (KAP) →
          </Link>
        </div>
      </header>

      {briefing ? (
        <BriefingWidget briefing={briefing} sourceLookup={sourceLookup} />
      ) : (
        <section className="rounded-lg border border-dashed border-neutral-300 bg-neutral-50 p-4 text-sm text-neutral-600">
          <strong className="font-semibold">Weekly briefing not yet generated.</strong> The
          first thematic summary will land after the next Sunday cron run.
          Raw TCMB &amp; BDDK feeds are available below in the meantime.
        </section>
      )}

      <section className="space-y-3">
        <header className="space-y-0.5">
          <h2 className="text-base font-semibold text-neutral-900">Raw feeds</h2>
          <p className="text-xs text-neutral-500">
            Source items the briefing draws from. Click through to the original release.
          </p>
        </header>
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          <SourceColumn source="tcmb" items={tcmb} />
          <SourceColumn source="bddk" items={bddk} />
        </div>
      </section>
    </main>
  );
}
