/**
 * /regulation — central-bank + banking-regulator announcements.
 *
 * Top: a weekly Kimi-generated thematic briefing (BBVA-style 6-column
 * grid) summarizing what changed in Turkish banking regulation. Below:
 * the raw TCMB + BDDK feeds for traceability and drill-down.
 *
 * Briefing is generated by scripts/summarize_regulations.py (Sunday
 * cron). Dashboard reads the latest row from regulation_briefings — no
 * LLM calls on page load.
 */
import Link from "next/link";
import {
  latestRegulationBriefing,
  newsBySource,
  newsLookupBySourceIds,
  newsSourceSummary,
  type Briefing,
} from "@/app/lib/news";
import RawFeeds from "./RawFeeds";

export const dynamic = "force-dynamic";

function fmtDate(iso: string): string {
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return iso.slice(0, 10);
  return d.toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" });
}

function BriefingWidget({
  briefing,
  sourceLookup,
}: {
  briefing: Briefing;
  sourceLookup: Map<string, { title: string; url: string; published_at: string }>;
}) {
  return (
    <section className="space-y-3">
      <header className="flex items-baseline justify-between flex-wrap gap-2">
        <div>
          <h2 className="text-base font-semibold text-neutral-900">Current Regulatory Snapshot</h2>
          <p className="text-xs text-neutral-500">
            AI-synthesized snapshot of macroprudential rules currently in force — grounded on TCMB&apos;s
            annual Monetary Policy framework and updated with {briefing.item_count} recent TCMB &amp; BDDK releases
          </p>
        </div>
        <div className="text-[11px] text-neutral-400 tabular-nums">
          generated {fmtDate(briefing.generated_at)} · {briefing.model}
        </div>
      </header>
      <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">
        {briefing.categories.map((cat) => (
          <div key={cat.name} className="rounded-lg border border-neutral-200 bg-white p-4 shadow-sm">
            <h3 className="text-sm font-semibold text-neutral-900 mb-2">{cat.name}</h3>
            <ul className="space-y-2">
              {cat.bullets.map((b, i) => (
                <li key={i} className="text-xs text-neutral-700 leading-snug">
                  <span className="text-neutral-400 mr-1">•</span>
                  {b.text}
                  {b.source_ids.length > 0 && (
                    <span className="ml-1 text-[10px] text-neutral-400">
                      {b.source_ids.map((id, idx) => {
                        const item = sourceLookup.get(id);
                        // Show the regulation's publication (effective) date,
                        // not the opaque source id; fall back to the id.
                        const label = item?.published_at ? fmtDate(item.published_at) : id;
                        return (
                          <span key={id}>
                            {idx > 0 && ", "}
                            {item ? (
                              <a
                                href={item.url}
                                target="_blank"
                                rel="noopener noreferrer"
                                className="hover:text-neutral-700 underline-offset-2 hover:underline tabular-nums"
                                title={`${item.title} (${id})`}
                              >
                                {label}
                              </a>
                            ) : (
                              <span>{id}</span>
                            )}
                          </span>
                        );
                      })}
                    </span>
                  )}
                </li>
              ))}
            </ul>
          </div>
        ))}
      </div>
    </section>
  );
}

export default async function RegulationPage() {
  const [briefing, tcmb, bddk, summary] = await Promise.all([
    latestRegulationBriefing(),
    newsBySource("tcmb", 50),
    newsBySource("bddk", 50),
    newsSourceSummary(),
  ]);

  // Build lookup for source-id chips in the briefing.
  const sourceLookup = briefing
    ? await newsLookupBySourceIds(
        briefing.categories.flatMap((c) =>
          c.bullets.flatMap((b) =>
            b.source_ids.map((id) => {
              const [src, ext] = id.split(":", 2);
              return { source: src, external_id: ext };
            }),
          ),
        ),
      )
    : new Map();

  const tcmbStats = summary.find((s) => s.source === "tcmb");
  const bddkStats = summary.find((s) => s.source === "bddk");

  return (
    <main className="px-8 py-8 space-y-8">
      <header className="space-y-1">
        <h1 className="text-2xl font-semibold tracking-tight">Regulation</h1>
        <p className="text-sm text-neutral-500">
          Central-bank press releases (TCMB) and banking-regulator board decisions (BDDK) — refreshed daily,
          thematic briefing refreshed weekly.
        </p>
        <div className="flex flex-wrap gap-4 text-xs text-neutral-500 pt-2">
          {tcmbStats && (
            <div>
              <span className="font-semibold text-neutral-700">TCMB</span> — {tcmbStats.total} items
              {tcmbStats.latest && (
                <span className="text-neutral-400"> · latest {fmtDate(tcmbStats.latest)}</span>
              )}
            </div>
          )}
          {bddkStats && (
            <div>
              <span className="font-semibold text-neutral-700">BDDK</span> — {bddkStats.total} items
              {bddkStats.latest && (
                <span className="text-neutral-400"> · latest {fmtDate(bddkStats.latest)}</span>
              )}
            </div>
          )}
          <Link
            href="/banks"
            className="text-neutral-600 underline hover:text-neutral-900"
          >
            Per-bank disclosures (KAP) →
          </Link>
        </div>
      </header>

      {briefing && briefing.categories.length > 0 ? (
        <BriefingWidget briefing={briefing} sourceLookup={sourceLookup} />
      ) : briefing ? (
        <section className="rounded-lg border border-dashed border-neutral-300 bg-neutral-50 p-4 text-sm text-neutral-600">
          <strong className="font-semibold">No regulatory rule changes detected in the past {briefing.window_days} days.</strong>
          {" "}The summarizer scanned {briefing.item_count} TCMB &amp; BDDK announcements
          on {fmtDate(briefing.generated_at)} but none qualified as a substantive
          rule change (caps, ratios, thresholds, or policy decisions). Raw feeds
          below show all administrative + market-commentary items.
        </section>
      ) : (
        <section className="rounded-lg border border-dashed border-neutral-300 bg-neutral-50 p-4 text-sm text-neutral-600">
          <strong className="font-semibold">Weekly briefing not yet generated.</strong> The
          first thematic summary will land after the next Sunday cron run.
          Raw TCMB &amp; BDDK feeds are available below in the meantime.
        </section>
      )}

      <RawFeeds tcmb={tcmb} bddk={bddk} />
    </main>
  );
}
