/**
 * News — the feed.
 *
 * Regulator announcements and press first, aggregator second, with a filter
 * between them. The LLM briefing sits at the top when there is one, and it
 * carries its own provenance line: which model wrote it, over what window, from
 * how many items. A generated summary is never shown as though it were a filed
 * figure — that line is the difference.
 *
 * Links open in the in-app browser rather than kicking out to Safari/Chrome, so
 * a reader can dismiss and keep their place in the feed.
 */
import * as WebBrowser from "expo-web-browser";
import { useState } from "react";
import { Pressable, View } from "react-native";

import { endpoints } from "../../api/client";
import type { NewsFeed } from "../../api/types";
import { useResource } from "../../api/use-resource";
import {
  ErrorState,
  Loading,
  Screen,
  ScreenHeader,
  StaleNote,
} from "../../components/screen";
import { Hairline, Label, Section, Text } from "../../components/ui";
import { ago } from "../../format";
import { useTheme } from "../../theme";

const FILTERS = [
  { key: "all", label: "ALL" },
  { key: "press", label: "REGULATORS" },
  { key: "google_news", label: "PRESS" },
] as const;

export default function NewsScreen() {
  const { colors, space } = useTheme();
  const [source, setSource] = useState<string>("all");

  // The key includes the filter, so each tab gets its own cache entry and
  // switching back is instant rather than a refetch.
  const { data, loading, refreshing, error, cachedAt, refresh } = useResource<NewsFeed>(
    `news:${source}`,
    endpoints.news(source, 50),
  );

  if (loading && !data) return <Screen><Loading /></Screen>;

  return (
    <Screen refreshing={refreshing} onRefresh={refresh}>
      <ScreenHeader title="News" record={data ? `${data.count} ITEMS` : undefined} />
      <StaleNote cachedAt={cachedAt} error={error} />

      {/* ── Filter ────────────────────────────────────────────────────── */}
      <View style={{ flexDirection: "row", gap: space.lg, paddingTop: space.md }}>
        {FILTERS.map((f) => (
          <Pressable key={f.key} onPress={() => setSource(f.key)} hitSlop={8}>
            <Label tone={source === f.key ? "default" : "faint"}>{f.label}</Label>
            {/* The active mark is a rule under the word, not a pill. */}
            <View
              style={{
                height: 1,
                marginTop: 3,
                backgroundColor: source === f.key ? colors.foreground : "transparent",
              }}
            />
          </Pressable>
        ))}
      </View>

      {!data ? (
        <ErrorState message={error?.message ?? "No data."} onRetry={refresh} />
      ) : (
        <>
          {/* ── Briefing ──────────────────────────────────────────────── */}
          {data.briefing && (
            <Section
              title="Regulatory briefing"
              meta={`${data.briefing.windowDays}d window`}
            >
              {data.briefing.categories.map((c) => (
                <View key={c.name} style={{ paddingTop: space.md }}>
                  <Label tone="muted">{c.name}</Label>
                  {c.bullets.map((b, i) => (
                    <Text key={i} size={14} tone="muted" style={{ marginTop: space.sm }}>
                      • {b.text}
                    </Text>
                  ))}
                </View>
              ))}
              <Label tone="faint" style={{ marginTop: space.lg }}>
                Generated by {data.briefing.model} from {data.briefing.itemCount} items ·{" "}
                {ago(data.briefing.generatedAt)}
              </Label>
            </Section>
          )}

          {/* ── Items ─────────────────────────────────────────────────── */}
          <Section title="Latest" meta={source === "all" ? "all sources" : source}>
            {data.items.map((n) => (
              <View key={n.id}>
                <Pressable
                  onPress={() => void WebBrowser.openBrowserAsync(n.url)}
                  style={({ pressed }) => ({
                    opacity: pressed ? 0.6 : 1,
                    paddingVertical: space.md,
                    gap: 4,
                  })}
                >
                  <Text size={15}>{n.title}</Text>
                  {n.summary ? (
                    <Text size={13} tone="muted" numberOfLines={2}>{n.summary}</Text>
                  ) : null}
                  <View style={{ flexDirection: "row", gap: space.sm, marginTop: 2 }}>
                    <Label>{n.source.toUpperCase()}</Label>
                    <Label tone="faint">{ago(n.publishedAt)}</Label>
                    {n.tickers && n.tickers.length > 0 && (
                      <Label tone="muted">{n.tickers.slice(0, 3).join(" · ")}</Label>
                    )}
                  </View>
                </Pressable>
                <Hairline />
              </View>
            ))}
          </Section>
        </>
      )}
    </Screen>
  );
}
