"""Render the Phase-0 census + drift sections into docs/AUDIT_BANK_CATALOG.md.

Reads data/audit_profiles.json (scripts/profile_audit_corpus.py) and rewrites
everything between the census markers in the catalogue. The rest of the file
stays hand-curated.

  python scripts/generate_audit_census.py
"""
from __future__ import annotations

import json
import sys
from collections import defaultdict
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
sys.stdout.reconfigure(encoding="utf-8")

PROFILES = REPO / "data" / "audit_profiles.json"
CATALOG = REPO / "docs" / "AUDIT_BANK_CATALOG.md"
BEGIN = "<!-- census:begin (generated by scripts/generate_audit_census.py — do not edit by hand) -->"
END = "<!-- census:end -->"

# Profile attributes compared quarter-over-quarter for the drift section.
_DRIFT_ATTRS = [
    ("language", lambda p: p.get("language")),
    ("bank_type", lambda p: p.get("bank_type")),
    ("bs_ncols", lambda p: (p.get("assets") or {}).get("ncols_modal")),
    ("text", lambda p: (p.get("assets") or {}).get("text_class")),
    ("sign", lambda p: (p.get("assets") or {}).get("sign_convention")),
    ("equity_at", lambda p: (p.get("liabilities") or {}).get("equity_numeral")),
]


def _fmt_set(values: set) -> str:
    vals = sorted(str(x) for x in values if x is not None)
    return "/".join(vals) if vals else "—"


def render(profiles: dict[str, dict]) -> str:
    by_bank: dict[str, dict[tuple[str, str], dict]] = defaultdict(dict)
    for key, prof in profiles.items():
        bank, period, kind = key.split("|")
        by_bank[bank][(period, kind)] = prof

    lines: list[str] = []
    lines.append(f"Census of {len(profiles)} report profiles across "
                 f"{len(by_bank)} banks (regenerated from data/audit_profiles.json).")
    lines.append("")
    lines.append("| Bank | Type | Reports | Periods | Lang | Text | Dipnot styles | Sign | BS cols | Equity at |")
    lines.append("|---|---|---|---|---|---|---|---|---|---|")
    for bank in sorted(by_bank):
        profs = list(by_bank[bank].values())
        periods = sorted({p for p, _ in by_bank[bank]})
        langs = {p.get("language") for p in profs}
        types = {p.get("bank_type") for p in profs}
        texts = {(p.get("assets") or {}).get("text_class") for p in profs}
        dipnots = {d for p in profs for d in (p.get("assets") or {}).get("dipnot_styles", [])}
        signs = {(p.get("assets") or {}).get("sign_convention") for p in profs}
        ncols = {(p.get("assets") or {}).get("ncols_modal") for p in profs}
        eq = {(p.get("liabilities") or {}).get("equity_numeral") for p in profs}
        lines.append(
            f"| {bank} | {_fmt_set(types)} | {len(profs)} | "
            f"{periods[0]}→{periods[-1]} | {_fmt_set(langs)} | {_fmt_set(texts)} | "
            f"{_fmt_set(dipnots)} | {_fmt_set(signs)} | {_fmt_set(ncols)} | {_fmt_set(eq)} |")

    # Drift: consecutive-period attribute changes per (bank, kind).
    lines.append("")
    lines.append("### Format drift (quarter-over-quarter changes)")
    lines.append("")
    drift_rows: list[str] = []
    for bank in sorted(by_bank):
        by_kind: dict[str, list[tuple[str, dict]]] = defaultdict(list)
        for (period, kind), prof in sorted(by_bank[bank].items()):
            by_kind[kind].append((period, prof))
        for kind, seq in by_kind.items():
            for (p0, a), (p1, b) in zip(seq, seq[1:]):
                changes = []
                for name, get in _DRIFT_ATTRS:
                    va, vb = get(a), get(b)
                    if va is not None and vb is not None and va != vb:
                        changes.append(f"{name} {va}→{vb}")
                if changes:
                    drift_rows.append(f"- **{bank}** {p0}→{p1} ({kind}): {', '.join(changes)}")
    lines.extend(drift_rows if drift_rows else ["- none observed"])

    # §4/§5 anchor coverage: how many reports contain each table.
    lines.append("")
    lines.append("### §4/§5 table inventory (reports containing each anchor)")
    lines.append("")
    anchor_counts: dict[str, int] = defaultdict(int)
    for prof in profiles.values():
        for key in (prof.get("anchors") or {}):
            anchor_counts[key] += 1
    lines.append("| Table | Reports | Share |")
    lines.append("|---|---|---|")
    n = max(len(profiles), 1)
    for key in sorted(anchor_counts, key=lambda k: -anchor_counts[k]):
        c = anchor_counts[key]
        lines.append(f"| {key} | {c} | {c * 100 // n}% |")

    # Statement-location gaps: reports where §2 pages weren't found at all.
    missing = [k for k, p in profiles.items()
               if "bs_assets" not in (p.get("section_pages") or {})]
    lines.append("")
    lines.append(f"### Reports with NO located balance sheet ({len(missing)})")
    lines.append("")
    for k in sorted(missing)[:40]:
        lines.append(f"- {k.replace('|', ' ')}")
    if len(missing) > 40:
        lines.append(f"- …and {len(missing) - 40} more")
    if not missing:
        lines.append("- none")
    return "\n".join(lines)


def main() -> int:
    profiles = json.loads(PROFILES.read_text(encoding="utf-8"))
    body = render(profiles)
    doc = CATALOG.read_text(encoding="utf-8")
    if BEGIN not in doc or END not in doc:
        sys.exit(f"census markers not found in {CATALOG}")
    pre = doc.split(BEGIN)[0]
    post = doc.split(END)[1]
    CATALOG.write_text(pre + BEGIN + "\n\n" + body + "\n\n" + END + post,
                       encoding="utf-8")
    print(f"[census] rendered {len(profiles)} profiles into {CATALOG}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
