"""Generate isolated web/Metro copies of the canonical mobile wire contract."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TARGETS = ["web/app/lib/app-api-contract.generated.ts", "mobile/src/api/contract.generated.ts"]

# The pure launch-decision module ships to both packages too. Each copy imports
# ITS package's generated contract, so the canonical import specifier is
# rewritten per target — nothing outside the package boundary is ever imported
# (Vitest's native transform resolves tsconfig per file, so a web test reaching
# into ../mobile dies in CI where mobile's node_modules is absent).
COMPAT_SOURCE = "contracts/compatibility-state.ts"
COMPAT_TARGETS = {
    "web/app/lib/compatibility-state.generated.ts": "./app-api-contract.generated",
    "mobile/src/api/compatibility-state.ts": "./contract.generated",
}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    errors = []
    text = "// Generated by scripts/sync_app_contract.py; edit contracts/app-api-v1.ts.\n" + (
        ROOT / "contracts/app-api-v1.ts").read_text(encoding="utf-8")
    compat = (ROOT / COMPAT_SOURCE).read_text(encoding="utf-8")
    for name in TARGETS:
        path = ROOT / name
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != text:
                errors.append(f"Stale generated contract: {name}")
        else:
            path.write_text(text, encoding="utf-8")
    for name, contract_import in COMPAT_TARGETS.items():
        body = compat.replace('from "./app-api-v1"', f'from "{contract_import}"')
        out = (f"// Generated by scripts/sync_app_contract.py; edit {COMPAT_SOURCE}.\n" + body)
        path = ROOT / name
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != out:
                errors.append(f"Stale generated compatibility state: {name}")
        else:
            path.write_text(out, encoding="utf-8")
    app = json.loads((ROOT / "mobile/app.json").read_text())["expo"]
    build = app["extra"]["clientBuild"]
    if type(build) is not int or build < 1 or build != app["android"]["versionCode"] or str(build) != app["ios"]["buildNumber"]:
        errors.append("Mobile clientBuild, Android versionCode and iOS buildNumber must agree")
    print("\n".join(errors) if errors else "Mobile wire contract and build numbers in sync")
    return bool(errors)


if __name__ == "__main__":
    raise SystemExit(main())
