"""Generate isolated web/Metro copies of the canonical mobile wire contract."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TARGETS = ["web/app/lib/app-api-contract.generated.ts", "mobile/src/api/contract.generated.ts"]


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    text = "// Generated by scripts/sync_app_contract.py; edit contracts/app-api-v1.ts.\n" + (
        ROOT / "contracts/app-api-v1.ts").read_text(encoding="utf-8")
    errors = []
    for name in TARGETS:
        path = ROOT / name
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != text:
                errors.append(f"Stale generated contract: {name}")
        else:
            path.write_text(text, encoding="utf-8")
    app = json.loads((ROOT / "mobile/app.json").read_text())["expo"]
    build = app["extra"]["clientBuild"]
    if type(build) is not int or build < 1 or build != app["android"]["versionCode"] or str(build) != app["ios"]["buildNumber"]:
        errors.append("Mobile clientBuild, Android versionCode and iOS buildNumber must agree")
    print("\n".join(errors) if errors else "Mobile wire contract and build numbers in sync")
    return bool(errors)


if __name__ == "__main__":
    raise SystemExit(main())
