// GENERATED by scripts/analyst/extract_stage_definitions.py — do not edit.
// Per-bank IFRS-9 staging thresholds as DISCLOSED in each bank's own §3/
// notes prose (the feasibility test's missing comparability dataset).
// Snippets are verbatim from the filing; days are parsed from them.
// Source: data/bank_audit_prose.db (local-only) — regenerate after a
// prose backfill and commit the result.

export interface StageDefinition {
  source_period: string;
  source_kind: string;
  dpd_stage2_days: number | null;
  stage2_snippet: string | null;
  dpd_stage3_days: number | null;
  stage3_snippet: string | null;
}

export const STAGE_DEFINITIONS: Record<string, StageDefinition> = {
  "AKTIF": {
    "source_period": "2026Q1",
    "source_kind": "consolidated",
    "dpd_stage2_days": null,
    "stage2_snippet": null,
    "dpd_stage3_days": 90,
    "stage3_snippet": "e ve temerrüde düşen ilave kredi tutarının SYR’ye etkisi hesaplanmaktadır. Ayrıca yine aylık olarak gerçekleştirilen senaryo analizinde, 61-90 gün gecikmedeki kredi tutarları üzerinden aylık roll rate oranları (61-90 gün gecikmedeki kredilerden takip hesaplarına intikal edenlerin oranı) hesaplanmakta, son"
  },
  "ALBRK": {
    "source_period": "2026Q1",
    "source_kind": "consolidated",
    "dpd_stage2_days": 30,
    "stage2_snippet": "at initial recognition or that do not have a significant increase in credit risk since initial recognition and the delay days do not exceed 30 days. Impairment for credit risk is recorded in the amount of 12-month expected credit losses. It is valid for all assets unless there is a significant deterioratio",
    "dpd_stage3_days": 90,
    "stage3_snippet": "conditions exist in accordance with the Parent Bank’s internal procedures, the related financial asset is evaluated as default: -Loans past 90 days from the last installment date - Loans restructured and classified as performing recievables and restructured in the 1-year monitoring period at least once aga"
  },
  "ALNTF": {
    "source_period": "2025Q4",
    "source_kind": "consolidated",
    "dpd_stage2_days": null,
    "stage2_snippet": null,
    "dpd_stage3_days": 90,
    "stage3_snippet": "ğunda temerrüdün ortaya çıkacağını ortaya koyan makul ve desteklenebilir bilgilere sahip olmadığı sürece temerrüdün, finansal aracın vadesi 90 gün geçtikten daha sonra meydana gelmeyeceğine yönelik aksi ispat edilebilir bir ön kabul vardır. Bu amaçlar için kullanılan temerrüt tanımı, diğer bir temerrüt ta"
  },
  "ANADOLU": {
    "source_period": "2026Q1",
    "source_kind": "consolidated",
    "dpd_stage2_days": null,
    "stage2_snippet": null,
    "dpd_stage3_days": 90,
    "stage3_snippet": "imali hesaplanır. Aşama 3 olarak sınıflanan kredilerde temerrüt ihtimali %100 olarak dikkate alınır. Temerrüt tanımı borca ilişkin ödemenin 90 gün gecikmiş olması veya gecikme olup olmadığına bakılmaksızın borcun ödenmeyeceğine kanaat getirilmesi olarak tanımlanmıştır. Temerrüt halinde kayıp (THK) oranı:"
  },
  "BURGAN": {
    "source_period": "2026Q1",
    "source_kind": "consolidated",
    "dpd_stage2_days": null,
    "stage2_snippet": null,
    "dpd_stage3_days": 90,
    "stage3_snippet": "ğunda temerrüdün ortaya çıkacağını ortaya koyan makul ve desteklenebilir bilgilere sahip olmadığı sürece temerrüdün, finansal aracın vadesi 90 gün geçtikten sonra meydana geleceğine yönelik bir ön kabul vardır. Bu amaçlar için kullanılan temerrüt tanımı, “diğer bir temerrüt tanımının belirli bir finansal"
  },
  "EXIM": {
    "source_period": "2026Q1",
    "source_kind": "unconsolidated",
    "dpd_stage2_days": null,
    "stage2_snippet": null,
    "dpd_stage3_days": 90,
    "stage3_snippet": "s a default on the relevant debt in the following two cases: - Objective Default Definition: It means that the debt is overdue by more than 90 days. - Subjective Default Definition: It means that it is determined the debt will not be paid off. If the borrower deemed to be unable to fulfill the debt obligat"
  },
  "GARAN": {
    "source_period": "2026Q2",
    "source_kind": "consolidated",
    "dpd_stage2_days": 30,
    "stage2_snippet": "ease in Credit Risk) where any of the following conditions are satisfied as a result of a qualitative assessment. - Loans overdue more than 30 days as of the reporting date, - Loans classified as watchlist, - When there is a change in the payment plan due to refinancing, restructuring or concession, the lo",
    "dpd_stage3_days": 90,
    "stage3_snippet": "It is considered a debt as default on these two below conditions; 1. Objective Default Definition: It means debt having past due more than 90 days. Current definition of default is based on a more than 90 days past due definition. If a loan is exactly 90 days past due, it will not be considered as default"
  },
  "HALKB": {
    "source_period": "2026Q1",
    "source_kind": "consolidated",
    "dpd_stage2_days": 30,
    "stage2_snippet": "ease in Credit Risk) if any of the following conditions determined through qualitative assessment are met: • Receivables that are more than 30 days past due as of the reporting date • Receivables classified under the “Under‑Monitoring” category • Restructuring arrangements granted to a borrower due to fina",
    "dpd_stage3_days": 90,
    "stage3_snippet": "relevant financial instruments. However, there is a rebuttable presumption that default does not occur later than when a financial asset is 90 days past due unless an entity has reasonable and supportable information to demonstrate that a more lagging default criterion is more appropriate. In accordance wi"
  },
  "HAYATK": {
    "source_period": "2026Q1",
    "source_kind": "consolidated",
    "dpd_stage2_days": 30,
    "stage2_snippet": "al asset. The Group classifies financial assets as stage 2, taking into account the following criteria: • Loans with overdue days exceeding 30 days but not exceeding 90 days, • Data received from the early warning system and the evaluation to be made by the Group in this case, • The Group’s management conc",
    "dpd_stage3_days": 90,
    "stage3_snippet": "s internal procedures, the relevant financial asset is within the scope of default if the following situations exist: • Loans that are over 90 days overdue from the last installment date (In this case, the customer is followed up on the 91st day). • Loans that are restructured and classified as live receiv"
  },
  "ICBCT": {
    "source_period": "2026Q1",
    "source_kind": "consolidated",
    "dpd_stage2_days": 30,
    "stage2_snippet": "ardaki temerrüt kayıtları • Borçlunun 90 gün üzerinde gecikme gün sayısına sahip olması • Borçlunun Aşama 3’ten Aşama 2’ye geçtikten sonra, 30 gün üzerinde gecikme gün sayısına sahip olması ya da yeniden yapılandırılması Beklenen zarar karşılığı hesaplamasına tabi olan finansal varlıkları ilk kez kayıtlar",
    "dpd_stage3_days": 90,
    "stage3_snippet": "konkordato başvurusu, iflas/iflas erteleme ve durumlar) ve ekonomik koşullar • Diğer finansal kuruluşlardaki temerrüt kayıtları • Borçlunun 90 gün üzerinde gecikme gün sayısına sahip olması • Borçlunun Aşama 3’ten Aşama 2’ye geçtikten sonra, 30 gün üzerinde gecikme gün sayısına sahip olması ya da yeniden"
  },
  "ISCTR": {
    "source_period": "2025Q4",
    "source_kind": "consolidated",
    "dpd_stage2_days": null,
    "stage2_snippet": null,
    "dpd_stage3_days": 90,
    "stage3_snippet": "credit loss. In order to classify a financial asset in the Stage 2, the following criteria is considered: - Overdue between 30-90 days - Restructuring of the loan - Significant deterioration in the probability of default In case of a significant deterioration in the probability of default, the"
  },
  "KLNMA": {
    "source_period": "2026Q2",
    "source_kind": "consolidated",
    "dpd_stage2_days": null,
    "stage2_snippet": null,
    "dpd_stage3_days": 90,
    "stage3_snippet": "ğunda temerrüdün ortaya çıkacağını ortaya koyan makul ve desteklenebilir bilgilere sahip olmadığı sürece temerrüdün, finansal aracın vadesi 90 gün geçtikten sonra meydana gelmeyeceğine yönelik aksi ispat edilebilir bir ön kabul vardır. Bu amaçlar için kullanılan temerrüt tanımı, diğer bir temerrüt tanımın"
  },
  "PASHA": {
    "source_period": "2026Q1",
    "source_kind": "unconsolidated",
    "dpd_stage2_days": 30,
    "stage2_snippet": "a alınmasından bu yana önemli ölçüde artmadığını varsayabilir” şeklinde açıklanmaktadır. Aşama 1’den Aşama 2’ye geçme için esas kriter olan 30 gün üzeri gecikme durumunda derecelendirme notu tekrar gözden geçirilir. Aşamalar arası geçişler için BDDK’nın ilgili yönetmelik/genelge ve yayımladığı bilgilendir",
    "dpd_stage3_days": null,
    "stage3_snippet": null
  },
  "QNBFB": {
    "source_period": "2026Q1",
    "source_kind": "consolidated",
    "dpd_stage2_days": 30,
    "stage2_snippet": "ease in Credit Risk) where any of the following conditions are satisfied as a result of a qualitative assessment: • Loans overdue more than 30 days as of the reporting date • Loans classified as watch-list • When there is a change in the payment plan due to restructuring Write-Off Policy Receivables that a",
    "dpd_stage3_days": 90,
    "stage3_snippet": "etime expected credit loss. In determining the impairment, the Parent Bank takes into consideration the following criteria: • Delay of over 90 days and impairment of creditworthiness • Collateral and/or equity of debtor is inadequate cover the payment of receivables on the maturity • In case the management"
  },
  "SKBNK": {
    "source_period": "2026Q1",
    "source_kind": "consolidated",
    "dpd_stage2_days": null,
    "stage2_snippet": null,
    "dpd_stage3_days": 90,
    "stage3_snippet": "tage): The Group takes into account the following criteria for the classification of a financial asset as a default; • Overdue by more than 90 days (150 days for leasing receivables) • The Group’s observation that the debtor cannot fulfill his / her debts related to the loan although it is not"
  },
  "TEB": {
    "source_period": "2026Q2",
    "source_kind": "consolidated",
    "dpd_stage2_days": 30,
    "stage2_snippet": "redi riskinde önemli artışın belirlenmesinde nitel ve nicel değerlendirmeler yapılmaktadır. Niteliksel değerlendirme: Kredi geri ödemesinde 30 gün üzeri gecikmesi olan alacaklar 2. Aşama krediler altında sınıflandırılır. Yeniden yapılandırılan krediler de yine bu aşama altında sınıflandırılmaktadır. Ayrıc",
    "dpd_stage3_days": null,
    "stage3_snippet": null
  },
  "TFKB": {
    "source_period": "2025Q4",
    "source_kind": "consolidated",
    "dpd_stage2_days": null,
    "stage2_snippet": null,
    "dpd_stage3_days": 90,
    "stage3_snippet": "eçmiş ancak değer düşüklüğüne uğramamış finansal varlıkların yaşlandırma analizi aşağıdaki gibidir: Cari Dönem (*) 0- 30 Gün 31- 60 Gün 61- 90 Gün Toplam"
  },
  "TOMK": {
    "source_period": "2025Q4",
    "source_kind": "unconsolidated",
    "dpd_stage2_days": null,
    "stage2_snippet": null,
    "dpd_stage3_days": 90,
    "stage3_snippet": "iş alacakların (90 günü geçenler) “karşılık ayrılan” olarak değerlendirilmeyen kısmı ve bu uygulamanın nedenleri Banka, vadesinin üzerinden 90 gün geçmiş olan kredileri Karşılıklar Yönetmeliği sınıflandırma hükümleri gereğince otomatik olarak takip hesaplarına aktarmakta ve ilgili sınıfının karşılığını ay"
  },
  "TSKB": {
    "source_period": "2026Q1",
    "source_kind": "consolidated",
    "dpd_stage2_days": 30,
    "stage2_snippet": "will be classified as Stage 2 (Significant Increase in Credit Risk) due to a significant increase in credit risk. - Loans overdue more than 30 days as of the reporting date - Loans classified as watchlist - When there is a change in the payment plan due to restructuring Expected credit loss provisions are",
    "dpd_stage3_days": 90,
    "stage3_snippet": "of the Parent Bank is made according to the following conditions: 1. Objective Default Definition: It means debt having past due more than 90 days. Current definition of default in the Parent Bank and its consolidated financial subsidiaries is based on a more than 90 days past due definition. 2. Subjectiv"
  },
  "VAKIFK": {
    "source_period": "2026Q1",
    "source_kind": "consolidated",
    "dpd_stage2_days": null,
    "stage2_snippet": null,
    "dpd_stage3_days": 90,
    "stage3_snippet": "Banka, temerrüt tanımında Basel II düzenlemeleri ve BDDK mevzuatı ile uyumlu olarak, borçlunun Ana Ortaklık Banka’ya olan yükümlülüklerini 90 gün veya daha uzun süreyle yerine getirmemesi durumunu temerrüt olarak kabul etmektedir. Kurumsal alacaklar için müşteri bazında temerrüt yaklaşımı benimsenmiş olu"
  },
  "YKBNK": {
    "source_period": "2026Q2",
    "source_kind": "consolidated",
    "dpd_stage2_days": 30,
    "stage2_snippet": "As of reporting date:  Lifetime expected credit losses shall be recognized on a transaction base, when more than 30 days past due status is passed. The Parent Bank can abandon this estimation when it has reasonable and supportable information about customers’ contractual repaymen",
    "dpd_stage3_days": 90,
    "stage3_snippet": "AD and on the effective interest rate. In particular:  The PD (Probability of Default), represents the customer’s probability of more than 90 days delay, within 12months;  The LGD (Loss Given Default), represents the percentage of the estimated loss, and thus the expected rate of recovery, at the date of"
  },
  "ZIRAAT": {
    "source_period": "2025Q4",
    "source_kind": "consolidated",
    "dpd_stage2_days": null,
    "stage2_snippet": null,
    "dpd_stage3_days": 90,
    "stage3_snippet": "n (90 günü geçenler) “karşılık ayrılan” olarak değerlendirilmeyen kısmı ve bu uygulamanın nedenleri Ana Ortaklık Banka, vadesinin üzerinden 90 gün geçmiş olan kredileri Karşılıklar Yönetmeliği sınıflandırma hükümleri gereğince otomatik olarak takip hesaplarına aktarmakta ve ilgili sınıfının karşılığını ay"
  },
  "ZIRAATD": {
    "source_period": "2025Q4",
    "source_kind": "unconsolidated",
    "dpd_stage2_days": null,
    "stage2_snippet": null,
    "dpd_stage3_days": 90,
    "stage3_snippet": "iş alacakların (90 günü geçenler) “karşılık ayrılan” olarak değerlendirilmeyen kısmı ve bu uygulamanın nedenleri Banka, vadesinin üzerinden 90 gün geçmiş olan kredileri Karşılıklar Yönetmeliği sınıflandırma hükümleri gereğince otomatik olarak takip hesaplarına aktarmalı ve ilgili sınıfının karşılığını ayı"
  },
  "ZIRAATK": {
    "source_period": "2026Q1",
    "source_kind": "consolidated",
    "dpd_stage2_days": 30,
    "stage2_snippet": "recede artmasının ve 2. aşamaya aktarılmasının belirlenmesinde dikkate alınan temel kriterler, yakın izlemede olması, gecikme gün sayısının 30 gün ve üzerinde olması ve Banka’nın içsel erken uyarı sistemi notudur.",
    "dpd_stage3_days": 90,
    "stage3_snippet": ", borcun temerrütte olduğunu değerlendirmektedir: - Objektif Temerrüt Tanımı: Borcun 90 günden fazla gecikmiş olması anlamına gelir. Borcun 90 gün gecikmiş olması ile birlikte temerrütte olma durumu 91. günde başlar. - Subjektif Temerrüt Tanımı: Borcun ödenmeyeceğine kanaat getirilmesi anlamına gelir. Bor"
  }
};

export const STAGE_DEFINITION_CENSUS = {
  "banks_scanned": 38,
  "banks_with_any": 24,
  "stage2_days_distribution": {
    "30": 11
  },
  "stage3_days_distribution": {
    "90": 22
  }
} as const;
